# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/data_server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pkg/data_server.proto\x12\x0b\x64\x61ta_server\"H\n\x0eRawDataRequest\x12\x16\n\x0e\x64\x61ta_file_name\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"0\n\x16GetTrainingDataRequest\x12\x16\n\x0e\x64\x61ta_file_name\x18\x01 \x01(\t\"[\n\x0bMoreRawData\x12\x16\n\x0e\x64\x61ta_file_name\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61ta_file_id\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\"%\n\rRemoveRequest\x12\x14\n\x0c\x64\x61ta_file_id\x18\x01 \x01(\t\"\x86\x01\n\x0eResponseStatus\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".data_server.ResponseStatus.Status\"@\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x0f\n\x0bIN_PROGRESS\x10\x03\"\x1c\n\x0cTrainingData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xce\x02\n\x13TrainingDataService\x12G\n\x07\x43onvert\x12\x1b.data_server.RawDataRequest\x1a\x1b.data_server.ResponseStatus(\x01\x30\x01\x12Q\n\x0fGetTrainingData\x12#.data_server.GetTrainingDataRequest\x1a\x19.data_server.TrainingData\x12L\n\x0f\x41\x64\x64TrainingData\x12\x18.data_server.MoreRawData\x1a\x1b.data_server.ResponseStatus(\x01\x30\x01\x12M\n\x12RemoveTrainingData\x12\x1a.data_server.RemoveRequest\x1a\x1b.data_server.ResponseStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.data_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RAWDATAREQUEST']._serialized_start=38
  _globals['_RAWDATAREQUEST']._serialized_end=110
  _globals['_GETTRAININGDATAREQUEST']._serialized_start=112
  _globals['_GETTRAININGDATAREQUEST']._serialized_end=160
  _globals['_MORERAWDATA']._serialized_start=162
  _globals['_MORERAWDATA']._serialized_end=253
  _globals['_REMOVEREQUEST']._serialized_start=255
  _globals['_REMOVEREQUEST']._serialized_end=292
  _globals['_RESPONSESTATUS']._serialized_start=295
  _globals['_RESPONSESTATUS']._serialized_end=429
  _globals['_RESPONSESTATUS_STATUS']._serialized_start=365
  _globals['_RESPONSESTATUS_STATUS']._serialized_end=429
  _globals['_TRAININGDATA']._serialized_start=431
  _globals['_TRAININGDATA']._serialized_end=459
  _globals['_TRAININGDATASERVICE']._serialized_start=462
  _globals['_TRAININGDATASERVICE']._serialized_end=796
# @@protoc_insertion_point(module_scope)
